### ISSUE TITLE
Research on Magic Labs KMS

### ISSUE THREAD

**Issue by Raushansingh184** [hypersign-protocol/hypersign-auth-node-sdk#33]
We would like to know how magic labs is managing the private keys

Need to read the following white paper and decipher that.

**Comment by Raushanabhishek** [comment]
https://www.dropbox.com/s/3flqaszoigwis5b/Magic%20Whitepaper.pdf?dl=0

**Comment by Raushanabhishek** [comment]
https://patents.google.com/patent/US20210092108A1/en?assignee=Magic+Labs%2c+Inc.  **Patent**

**Comment by vikramIde** [comment]
@Raushanabhishek  status report please!

**Comment by Raushanabhishek** [comment]
Hi vikramIde,
My First research is completed on the magic link for new users. Please find below the sequential diagram.
[Untitled Diagram.drawio (1).pdf](https://github.com/hypersign-protocol/hypersign-auth-node-sdk/files/7966317/Untitled.Diagram.drawio.1.pdf)

**Comment by vikramIde** [comment]
Looks good, need to get all the other diagrams and flows sorted

**Comment by Raushanabhishek** [comment]
Steps:
************************************************************************
1. New users will onboard in the client system & the client browser will send the user's email id as a request to Magic Auth Relayer System.
2. Client browser will generate public & private keys.
3. The Magic Auth Relayer will respond time bound access token to the client browser.
4. The Client browser will request for Scoped credential to AWS KMS & send the received time-bound access token as a request.
5.  The AWS KMS will respond Scoped credential to the client browser.
6. The Client browser will request for the encrypted private key to AWS KMS & Send the received Scope credential as a header & private key as a body of the request payload.
7. The AWS KMS will respond an encrypted private key(encrypted hash) to the client browser.
8. The Client browser will store the received encrypted hash on the browser & the magic auth relayer system will store the received encrypted key as a key-value pair & key will be the end user's email id.

**Comment by Raushanabhishek** [comment]
For a demo of Magic Labs KMS. Please follow below mentioned link.
https://codesandbox.io/s/github/MagicLabs/example-web3?file=/index.html
